### ISSUE TITLE
Battery Polarity Warning

### ISSUE THREAD

**Issue by carl3** [getchip/CHIP-Docs#12]
In the "Power From A Battery" it would be good to add a note that the black (-) wire should be on the outside edge and/or add text and arrow to the image. I bought a lipo battery that came without the connector, so bought a pack of connector wires from ebay. Apparently there is a type A and type B JST-PH 2.0mm connector with reversed red and black wiring. Most of the connector packs sold on ebay are the wrong polarity and need to be soldered with crossed colors! I didn't check at first so inserted my battery reversed-- fortunately I didn't burn out anything. Thankfully, there must be a reversed battery protection circuit.

**Comment by nyboer** [comment]
Thanks for the note. I'll update.
