### ISSUE TITLE
Typo in linux web flasher instructions

### ISSUE THREAD

**Issue by keijukainen** [getchip/CHIP-Docs#25]
https://docs.getchip.com/chip.html#web-flasher-os-specific-issues

I'm not sure if this issue is specific to my OS but my bash terminal doesn't recognize the parentheses around the USER variable.  Use the following instead:

`sudo usermod -a -G dialout ${USER}`
`sudo usermod -a -G plugdev ${USER}`

**Comment by keijukainen** [comment]
The docs should also mention that some linux distributions may require the commands below.

`sudo groupadd dialout`
`sudo groupadd plugdev`

**Comment by laraCat** [comment]
Added. This repo is being discontinued.
