### ISSUE TITLE
Over USB tether setup advice missing ..

### ISSUE THREAD

**Issue by ph-hs** [getchip/CHIP-Docs#3]
specifically for people that don't have the composite video cable.

topics: nmtui versus nmcli.
- their varying availaibily on Macs and different flavors/versions of Linux

**Comment by nyboer** [comment]
The section http://docs.getchip.com/chip.html#headless-chip covers several options for using CHIP without a monitor/keyboard setup.
We don't want to document the variety of network manager interfaces here.
