### ISSUE TITLE
Accessing UART (not via UART)

### ISSUE THREAD

**Issue by wernight** [getchip/CHIP-Docs#5]
_making.md should state how to read UART, that is how to use CHIP to access and read/write another device's UART. That would allow connecting to a microcontroller or other peripheral which has a serial interface.

Seems that a decent starting place for that is:
http://elinux.org/RPi_Serial_Connection

**Comment by nyboer** [comment]
Thanks for the suggestion. It's not a fundamental CHIP operation, though, so I think this would be better for the NTC forums https://bbs.nextthing.co/c/CHIP or the community wiki http://www.chip-community.org/index.php/Main_Page

**Comment by wernight** [comment]
Opened https://bbs.nextthing.co/t/how-to-use-uart-as-serial-connection-port/8889; may be worth updating the doc once a solution is found.
